# Build the SDK ARP source with a small explicit-netif extension in the same TU.
# The SDK file is never patched. A framework layout change fails at configure.
idf_component_get_property(_lwip_lib lwip COMPONENT_LIB)
get_target_property(_lwip_sources ${_lwip_lib} SOURCES)
set(_arp_found FALSE)
set(_lwip_sources_new "")
foreach(_source IN LISTS _lwip_sources)
    if(_source MATCHES "(^|/)etharp[.]c$")
        set(_arp_found TRUE)
        if(NOT IS_ABSOLUTE "${_source}")
            idf_component_get_property(_lwip_dir lwip COMPONENT_DIR)
            set(_source "${_lwip_dir}/${_source}")
        endif()
        set(_arp_generated "${CMAKE_BINARY_DIR}/tsr_etharp.c")
        file(WRITE "${_arp_generated}" "#include \"${_source}\"\n#include \"${CMAKE_SOURCE_DIR}/components/dhcpserver/etharp_netif.inc\"\n")
        list(APPEND _lwip_sources_new "${_arp_generated}")
    else()
        list(APPEND _lwip_sources_new "${_source}")
    endif()
endforeach()
if(NOT _arp_found)
    message(FATAL_ERROR "Cannot find lwIP etharp.c for explicit AP netif support")
endif()
set_property(TARGET ${_lwip_lib} PROPERTY SOURCES ${_lwip_sources_new})
# Leave room for all AP stations plus gateway and temporary DHCP entries.
target_compile_definitions(${_lwip_lib} PUBLIC ARP_TABLE_SIZE=64)
